name: 01-Building-Blocks    

on: workflow_dispatch       

jobs:
      
    echo-hello:
         runs-on: ubuntu-latest
         steps:
            - name: Say hello
              run: echo "Hello World!"
    
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Sucessful Step
              run: |
                echo "i will Suceed"
                exit 0
            - name: Say good bye
              run: echo "good bye!"



# name: Defines the name of the workflow
# on: Specifies the event that triggers the workflow
# jobs: Defines a collection of jobs to be run
# Job ID (custom name for the job)
# runs-on: Specifies the type of runner (e.g., ubuntu, windows)
# environment:prod when the environment is prod
# defaults: Sets default values for all steps in the job (cd directory)
# steps: A sequence of tasks to be run as part of the job
# name: Human-readable name for the step
# run: Executes shell commands

 # Another job




# events are triggers
# runners are VMs

# run-name: keyword is used to dynamically name a workflow run
# workflow_dispatch:  # Allows manual triggering from the GitHub UI
# types: Filters specific activity types within the pull_request event
# branches: Limits the trigger to specific branches
# inputs: Defines inputs for manually triggered workflows
# debug: Name of the input
# type: Declares the input type (boolean, string, etc.)
# default: Specifies a default value if input is not provided

# env: Declares environment variables at the workflow level (available to all jobs/steps)
# env: Declares environment variables at the job level (available to all steps in the job)
# env: Step-level environment variables (overrides job/workflow level)


# if: ${{ inputs.debug }}  # conditional execution expression
# shell: bash  # Overrides the default shell to use bash on Windows
# uses: Calls a pre-built GitHub Action (here, to checkout repo code)
# with: Supplies input parameters to the action above (uses keyword)

# having default values using OR condition
# run-name: 07- using expressions DEBUG -  ${{ inputs.debug && 'ON' || 'OFF' }}
 
##contexts
# ${{ github.event_name}}
# ${{ env.MY_OVERWRITTEN_VAR}}   ## here the keyword env is used is refreed
# ${{ vars.MY_VAR}}              ## setup in cloud variables and refferred
# $MY_OVERWRITTEN_VAR


## Create ORAGNIZATION Variables
## ORG_VAR = organization value 1
## OVERWRITTEN_VAR = = organization value 2

## Create Repository Variables
## REPOSITORY_VAR = repository value 1



## Create environment staging
## TARGET_VAR = staging

## Create environment production
## TARGET_VAR = production
## OVERWRITTEN_VAR = = prod value

#3 environment are valid fpor a repository only 

#Repository Variables- visibility only to workflows within that specific repository
#Organization Variables - Can be shared across multiple repositories within the organization.You must explicitly select which repositories can access the variable
#Environment Variables - Specific environment like prod, dev, etc.