               
name: 04-using-actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: 04-using-actions/react-app

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'

      - name: Install Dependencies
        run : |
              ls -R
              npm ci

      - name: Run unit Tests
        run: npm run test

        


# 0. checkout the code from the repo
# 1. install dependencies of react application
# 2. Execute automated tests
# create react application
# mkdir folder
# cd folder
# npx create-react-app --template typescript react-app
# y
# cd create-react-app
# npm start

# run: |
# cd .github\workflows\react-app
# npm ci



