               
name: 04-using-actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
      - name: Install Dependencies
        run : npm ci
        working-directory: .github/workflows/react-app



# 0. checkout the code from the repo
# 1. install dependencies of react application
# 2. Execute automated tests
# create react application
# mkdir folder
# cd folder
# npx create-react-app --template typescript react-app
# npm run start

# run: |
# cd .github\workflows\react-app
# npm ci

