               
name: 05-filters-ativity-types

on: 
    pull_request:
      types:
        - closed
      branches:
        - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "running whenever PR is closed"
