               
name: 05-filters-ativity-types

on: 
    pull_request:
      types:
        - opened
        - synchronize
      branches:
        - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "running whenever PR is opened or synchronized and base branch is main"
